import supabase from '../config/supabase.client';

interface UploadFileParams {
    file: Express.Multer.File;
    bucket: string; // The bucket name (e.g., 'avatars', 'documents')
    folder?: string; // Optional folder path within the bucket
}

export const fileUploadService = {
    /**
     * Uploads a file to Supabase Storage and returns the public URL and storage ID.
     * @param file - The Multer file object
     * @param bucket - The Supabase storage bucket name
     * @param folder - Optional folder path
     * @returns Promise<{ publicUrl: string; id: string }> - The public URL and storage ID of the uploaded file
     */
    async uploadFile({ file, bucket, folder }: UploadFileParams): Promise<{ publicUrl: string; id: string }> {
        try {
            // Generate a unique filename to prevent collisions
            const timestamp = Date.now();
            const randomString = Math.random().toString(36).substring(2, 15);
            // Sanitize original filename to remove special characters but keep extension
            const cleanOriginalName = file.originalname.replace(/[^a-zA-Z0-9.]/g, '_');
            const uniqueFilename = `${timestamp}_${randomString}_${cleanOriginalName}`;

            // Construct the full file path including folder if provided
            const filePath = folder
                ? `${folder.replace(/\/$/, '')}/${uniqueFilename}`
                : uniqueFilename;

            // Upload the file to Supabase
            const { data, error } = await supabase.storage
                .from(bucket)
                .upload(filePath, file.buffer, {
                    contentType: file.mimetype,
                    upsert: false
                });

            if (error) {
                console.error('Supabase upload error:', error);
                throw new Error(`Upload failed: ${error.message}`);
            }

            // Get the public URL
            const { data: publicUrlData } = supabase.storage
                .from(bucket)
                .getPublicUrl(filePath);

            return {
                publicUrl: publicUrlData.publicUrl,
                id: (data as any).id // This is the payment id/file id generated by supabase storage
            };
        } catch (error) {
            console.error('File upload service error:', error);
            throw error;
        }
    },

    /**
     * Deletes a file from Supabase Storage (Helper for cleanup if needed)
     */
    async deleteFile(bucket: string, path: string): Promise<void> {
        const { error } = await supabase.storage
            .from(bucket)
            .remove([path]);

        if (error) {
            throw new Error(`Delete failed: ${error.message}`);
        }
    }
};
